name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_RIVER_009BE6C03 }}
          action: "upload"
          app_location: "/"         # index.html in repo root
          api_location: ""          # no API
          output_location: ""       # IMPORTANT: empty for plain HTML
          deployment_environment: "Production"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
